"""Locators for Checkout page"""

checkout_link = "shopping_cart_link"
checkout_cart_list = "cart_list"
checkout_cart_item = "cart_item"
btn_checkout = "checkout"
txt_first_name = "first-name"
txt_last_name = "last-name"
txt_postal_code = "postal-code"
btn_continue = "continue"
btn_finish = "finish"
txt_success = "complete-header"
